package com.nt.beans;

import org.springframework.beans.factory.annotation.Lookup;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

@Component("container")
@Scope("singleton")
public abstract class WebContainer  {

	public WebContainer() {
		System.out.println("WebContainer:: 0-param constructor ::"+this.getClass()+"......."+this.getClass().getSuperclass());
	}
	
	//@Lookup    // alternate to <lookup-method>
	@Lookup("handler")
	public abstract    RequestHandler  createRequestHandler();
	
	public   void  processRequest(String data) {
		RequestHandler handler=null;
		System.out.println("WebContainer is processing request with data::"+data+ "by giving it to handler");
		//get Dependent object using dependency lookup code generated by the container...
		handler=createRequestHandler();
		//use dependent object..
		handler.handleRequest(data);
	}

	

}
