package com.nt.beans;

public interface WebContainer  {
	
	/*public WebContainer() {
		System.out.println("WebContainer:: 0-param constructor ::"+this.getClass()+"......."+this.getClass().getSuperclass());
	}*/
	    RequestHandler  createRequestHandler();
	
	default   void  processRequest(String data) {
		RequestHandler handler=null;
		System.out.println("WebContainer is processing request with data::"+data+ "by giving it to handler");
		//get Dependent object using dependency lookup code generated by the container...
		handler=createRequestHandler();
		//use dependent object..
		handler.handleRequest(data);
	}
}
