package com.nt.beans;

public abstract class WebContainer  {

	public WebContainer() {
		System.out.println("WebContainer:: 0-param constructor ::"+this.getClass()+"......."+this.getClass().getSuperclass());
	}
	
	public abstract    RequestHandler  createRequestHandler();
	
	public   void  processRequest(String data) {
		RequestHandler handler=null;
		System.out.println("WebContainer is processing request with data::"+data+ "by giving it to handler");
		//get Dependent object using dependency lookup code generated by the container...
		handler=createRequestHandler();
		//use dependent object..
		handler.handleRequest(data);
	}

	

}
